apiVersion: skaffold/v4beta5
kind: Config

build:
  artifacts:
  - image: hulkdx/ff-pro
    context: ../
    custom:
      buildCommand: |
        set -e
        GOOS=linux make build
        cat <<EOF | docker build --tag=$IMAGE -f - "$BUILD_CONTEXT"
            FROM golang:1.21.3-alpine
            COPY build/app app
            ENTRYPOINT [ "./app" ]
        EOF
      dependencies:
        paths:
          - "**/*"

manifests:
  kustomize:
    paths:
      - ../deploy/dev
deploy:
  tolerateFailuresUntilDeadline: true
  kubectl: {}
