name: Pull-requests

on:
  pull_request:
    branches: [ "main" ]

env:
  API_DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/ff-pro:v1
  TTL_DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/ff-pro-ttl:v1

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run tests
      run: make test

    - name: Build server
      run: make build
