name: Pull-requests

on:
  pull_request:
    branches: [ "main" ]

env:
  API_DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/ff-pro:v1
  TTL_DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/ff-pro-ttl:v1

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run tests
      run: make test

    - name: Build server
      run: make build

    - name: docker build api
      env:
        DOCKER_IMAGE_NAME: ${{ env.API_DOCKER_IMAGE_NAME }}
        APP_CMD_PATH: ./cmd/api
      run: make docker-build

    - name: docker build ttl
      env:
        DOCKER_IMAGE_NAME: ${{ env.TTL_DOCKER_IMAGE_NAME }}
        APP_CMD_PATH: ./cmd/booking-holds-ttl 
      run: make docker-build

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_API_KEY }}

    - name: docker push
      run: |
        docker push ${API_DOCKER_IMAGE_NAME} &> /dev/null
        docker push ${TTL_DOCKER_IMAGE_NAME} &> /dev/null
