name: Pull-requests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      working-directory: professional-service
      run: go test ./...

    - name: Build server
      working-directory: professional-service
      run: go build cmd/httpserver/main.go
