# TODO: deploy to k8s
name: deploy-to-kubernetes

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/ff-pro:v1

jobs:
  deploy:
    name: build and deploy to kubernetes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build server
      run: docker build . -t ${DOCKER_IMAGE_NAME}

    - name: docker push
      run: |
        docker login --username ${{ secrets.DOCKER_USER }} --password-stdin <<< ${{ secrets.DOCKER_API_KEY }} &> /dev/null
        docker push ${DOCKER_IMAGE_NAME} &> /dev/null
